spring:
  application:
    name: inventory-app-hexagonal

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${MONGO_URI:mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:my-secret-pw}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:inventorydb}?authSource=${MONGO_AUTH_DB:admin}}}

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:inventorydb}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${DATABASE_MAX_POOL_SIZE:5}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    defer-datasource-initialization: ${JPA_DEFER_DATASOURCE_INIT:true}

server:
  port: 8080

app:
  persistence:
    type: ${APP_PERSISTENCE_TYPE:jpa}
