spring:
  application:
    name: inventory-app-hexagonal

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:inventorydb}?currentSchema=${SCHEMA_NAME:public}&ssl=false
    username: ${DATABASE_USERNAME:mup-username}
    password: ${DATABASE_PASSWORD:mup-password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true # Ensures tables exist before data.sql runs

server:
  port: 8080

app:
  persistence:
    type: ${APP_PERSISTENCE_TYPE:jpa}
